// =============================================================================
// SMOOTH BUILDER PRO - EXPORT SERVICE
// =============================================================================

import type { Project, Section } from '../types';

// =============================================================================
// HTML GENERATION
// =============================================================================

function generateSectionHTML(section: Section): string {
  const content = section.content as Record<string, any>;
  const styles = section.settings || {};

  switch (section.type) {
    case 'header':
      return `
<header class="site-header">
  <div class="container">
    <a href="/" class="logo">${escapeHtml(content.logoText || 'Logo')}</a>
    <nav class="nav">
      ${(content.navigation || []).map((item: any) => 
        `<a href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a>`
      ).join('\n      ')}
    </nav>
    ${content.cta ? `<a href="${escapeHtml(content.cta.href)}" class="btn btn-primary">${escapeHtml(content.cta.label)}</a>` : ''}
  </div>
</header>`;

    case 'hero':
      return `
<section class="hero" style="background-color: ${styles.backgroundColor || '#ffffff'}">
  <div class="container">
    <h1>${escapeHtml(content.headline || '')}</h1>
    <p class="hero-subline">${escapeHtml(content.subline || '')}</p>
    <div class="hero-buttons">
      ${content.primaryCta ? `<a href="${escapeHtml(content.primaryCta.href)}" class="btn btn-primary">${escapeHtml(content.primaryCta.label)}</a>` : ''}
      ${content.secondaryCta ? `<a href="${escapeHtml(content.secondaryCta.href)}" class="btn btn-secondary">${escapeHtml(content.secondaryCta.label)}</a>` : ''}
    </div>
  </div>
</section>`;

    case 'services':
      return `
<section class="services" id="services">
  <div class="container">
    <h2>${escapeHtml(content.headline || '')}</h2>
    ${content.subline ? `<p class="section-subline">${escapeHtml(content.subline)}</p>` : ''}
    <div class="services-grid">
      ${(content.items || []).map((item: any) => `
      <div class="service-card">
        <div class="service-icon">${item.icon || '📦'}</div>
        <h3>${escapeHtml(item.title)}</h3>
        <p>${escapeHtml(item.description)}</p>
      </div>`).join('')}
    </div>
  </div>
</section>`;

    case 'contact':
      return `
<section class="contact" id="contact">
  <div class="container">
    <h2>${escapeHtml(content.headline || '')}</h2>
    <div class="contact-info">
      ${content.email ? `<p><strong>E-Mail:</strong> <a href="mailto:${escapeHtml(content.email)}">${escapeHtml(content.email)}</a></p>` : ''}
      ${content.phone ? `<p><strong>Telefon:</strong> <a href="tel:${content.phone.replace(/\s/g, '')}">${escapeHtml(content.phone)}</a></p>` : ''}
      ${content.address ? `<p><strong>Adresse:</strong><br>${escapeHtml(content.address).replace(/\n/g, '<br>')}</p>` : ''}
    </div>
    ${content.showForm ? `
    <form class="contact-form" onsubmit="handleSubmit(event)">
      <input type="text" name="name" placeholder="Name" required>
      <input type="email" name="email" placeholder="E-Mail" required>
      <textarea name="message" placeholder="Nachricht" rows="4" required></textarea>
      <button type="submit" class="btn btn-primary">Nachricht senden</button>
    </form>` : ''}
  </div>
</section>`;

    case 'footer':
      return `
<footer class="site-footer">
  <div class="container">
    <div class="footer-content">
      <p class="footer-company">${escapeHtml(content.companyName || '')}</p>
      ${content.description ? `<p class="footer-desc">${escapeHtml(content.description)}</p>` : ''}
      <div class="footer-links">
        ${(content.links || []).map((link: any) => 
          `<a href="${escapeHtml(link.href)}">${escapeHtml(link.label)}</a>`
        ).join(' | ')}
      </div>
      <p class="footer-copyright">${escapeHtml(content.copyright || '')}</p>
    </div>
  </div>
</footer>`;

    default:
      return `<!-- ${section.type} section -->`;
  }
}

function generateCSS(project: Project): string {
  const { colors, fonts, borderRadius } = project.theme;
  const radius = borderRadius === 'none' ? '0' : 
                 borderRadius === 'sm' ? '4px' : 
                 borderRadius === 'md' ? '8px' : 
                 borderRadius === 'lg' ? '12px' : '16px';

  return `/* Generated by Smooth Builder Pro */
:root {
  --color-primary: ${colors.primary};
  --color-secondary: ${colors.secondary};
  --color-accent: ${colors.accent};
  --color-background: ${colors.background};
  --color-text: ${colors.text};
  --color-text-muted: ${colors.textMuted};
  --font-heading: '${fonts.heading}', system-ui, sans-serif;
  --font-body: '${fonts.body}', system-ui, sans-serif;
  --radius: ${radius};
}

* { box-sizing: border-box; margin: 0; padding: 0; }

html { scroll-behavior: smooth; }

body {
  font-family: var(--font-body);
  color: var(--color-text);
  background: var(--color-background);
  line-height: 1.6;
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  line-height: 1.2;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1.5rem;
}

/* Header */
.site-header {
  position: sticky;
  top: 0;
  background: white;
  border-bottom: 1px solid #e5e7eb;
  padding: 1rem 0;
  z-index: 100;
}

.site-header .container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 2rem;
}

.logo {
  font-family: var(--font-heading);
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--color-primary);
  text-decoration: none;
}

.nav {
  display: flex;
  gap: 2rem;
}

.nav a {
  color: var(--color-text);
  text-decoration: none;
  transition: color 0.2s;
}

.nav a:hover {
  color: var(--color-primary);
}

/* Buttons */
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0.75rem 1.5rem;
  border-radius: var(--radius);
  font-weight: 500;
  text-decoration: none;
  transition: all 0.2s;
  cursor: pointer;
  border: none;
}

.btn-primary {
  background: var(--color-primary);
  color: white;
}

.btn-primary:hover {
  opacity: 0.9;
}

.btn-secondary {
  background: transparent;
  border: 2px solid var(--color-text);
  color: var(--color-text);
}

.btn-secondary:hover {
  background: var(--color-text);
  color: white;
}

/* Hero */
.hero {
  padding: 6rem 0;
  text-align: center;
}

.hero h1 {
  font-size: 3rem;
  margin-bottom: 1.5rem;
  color: var(--color-text);
}

.hero-subline {
  font-size: 1.25rem;
  color: var(--color-text-muted);
  max-width: 600px;
  margin: 0 auto 2rem;
}

.hero-buttons {
  display: flex;
  gap: 1rem;
  justify-content: center;
  flex-wrap: wrap;
}

/* Services */
.services {
  padding: 5rem 0;
}

.services h2 {
  font-size: 2.5rem;
  text-align: center;
  margin-bottom: 1rem;
}

.section-subline {
  text-align: center;
  color: var(--color-text-muted);
  margin-bottom: 3rem;
}

.services-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 2rem;
}

.service-card {
  background: white;
  padding: 2rem;
  border-radius: var(--radius);
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
  text-align: center;
}

.service-icon {
  font-size: 2.5rem;
  margin-bottom: 1rem;
}

.service-card h3 {
  font-size: 1.25rem;
  margin-bottom: 0.5rem;
}

.service-card p {
  color: var(--color-text-muted);
  font-size: 0.9rem;
}

/* Contact */
.contact {
  padding: 5rem 0;
  background: #f9fafb;
}

.contact h2 {
  font-size: 2.5rem;
  text-align: center;
  margin-bottom: 2rem;
}

.contact-info {
  text-align: center;
  margin-bottom: 2rem;
}

.contact-info p {
  margin-bottom: 0.5rem;
}

.contact-form {
  max-width: 500px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.contact-form input,
.contact-form textarea {
  padding: 0.75rem 1rem;
  border: 1px solid #e5e7eb;
  border-radius: var(--radius);
  font-family: inherit;
  font-size: 1rem;
}

.contact-form input:focus,
.contact-form textarea:focus {
  outline: none;
  border-color: var(--color-primary);
}

/* Footer */
.site-footer {
  background: #1f2937;
  color: white;
  padding: 3rem 0;
}

.footer-content {
  text-align: center;
}

.footer-company {
  font-weight: 600;
  font-size: 1.25rem;
  margin-bottom: 0.5rem;
}

.footer-desc {
  color: #9ca3af;
  margin-bottom: 1rem;
}

.footer-links {
  margin-bottom: 1rem;
}

.footer-links a {
  color: #9ca3af;
  text-decoration: none;
}

.footer-links a:hover {
  color: white;
}

.footer-copyright {
  color: #6b7280;
  font-size: 0.875rem;
}

/* Responsive */
@media (max-width: 768px) {
  .hero h1 { font-size: 2rem; }
  .services h2, .contact h2 { font-size: 2rem; }
  .nav { display: none; }
}
`;
}

function generateJS(): string {
  return `// Generated by Smooth Builder Pro
document.addEventListener('DOMContentLoaded', function() {
  // Smooth scroll for anchor links
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function(e) {
      e.preventDefault();
      const target = document.querySelector(this.getAttribute('href'));
      if (target) {
        target.scrollIntoView({ behavior: 'smooth' });
      }
    });
  });
});

// Contact form handler
function handleSubmit(event) {
  event.preventDefault();
  const form = event.target;
  const data = new FormData(form);
  
  // Form submission - customize as needed for your backend
  console.log('Form submitted:', Object.fromEntries(data));
  alert('Vielen Dank für Ihre Nachricht!');
  form.reset();
}
`;
}

function generateFullHTML(project: Project, inline: boolean = false): string {
  const { fonts } = project.theme;
  const sectionsHTML = project.sections
    .filter(s => s.enabled)
    .sort((a, b) => a.order - b.order)
    .map(s => generateSectionHTML(s))
    .join('\n');

  const css = generateCSS(project);
  const js = generateJS();

  return `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="${escapeHtml(project.seo.description)}">
  <title>${escapeHtml(project.seo.title || project.name)}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=${fonts.heading.replace(' ', '+')}:wght@400;500;600;700&family=${fonts.body.replace(' ', '+')}:wght@400;500;600&display=swap" rel="stylesheet">
  ${inline ? `<style>${css}</style>` : '<link rel="stylesheet" href="styles.css">'}
</head>
<body>
${sectionsHTML}
${inline ? `<script>${js}</script>` : '<script src="main.js"></script>'}
</body>
</html>`;
}

// =============================================================================
// EXPORT FUNCTIONS
// =============================================================================

export async function exportToZip(project: Project): Promise<void> {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();

  // Add files
  zip.file('index.html', generateFullHTML(project, false));
  zip.file('styles.css', generateCSS(project));
  zip.file('main.js', generateJS());
  zip.file('README.md', `# ${project.name}

Diese Website wurde mit Smooth Builder Pro erstellt.

## Dateien
- \`index.html\` - Hauptseite
- \`styles.css\` - Stylesheet
- \`main.js\` - JavaScript

## Hosting
Laden Sie alle Dateien auf Ihren Webserver hoch.

---
Erstellt mit ❤️ von Smooth Builder Pro
`);

  // Generate and download
  const blob = await zip.generateAsync({ type: 'blob' });
  downloadBlob(blob, `${slugify(project.name)}-website.zip`);
}

export async function exportToHTML(project: Project): Promise<void> {
  const html = generateFullHTML(project, true);
  const blob = new Blob([html], { type: 'text/html' });
  downloadBlob(blob, `${slugify(project.name)}.html`);
}

// =============================================================================
// HELPERS
// =============================================================================

function escapeHtml(str: string): string {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[äàáâ]/g, 'a')
    .replace(/[öòóô]/g, 'o')
    .replace(/[üùúû]/g, 'u')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
